
package org.example.soapperfume;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PerfumeTransactionSoapServiceImplService", targetNamespace = "http://soap.perfume.hccis.ca/", wsdlLocation = "http://localhost:8083/perfumetransactionsoapservice?wsdl")
public class PerfumeTransactionSoapServiceImplService
    extends Service
{

    private final static URL PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://soap.perfume.hccis.ca/", "PerfumeTransactionSoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/perfumetransactionsoapservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PerfumeTransactionSoapServiceImplService() {
        super(__getWsdlLocation(), PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public PerfumeTransactionSoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public PerfumeTransactionSoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public PerfumeTransactionSoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public PerfumeTransactionSoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PerfumeTransactionSoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PerfumeTransactionSoapService
     */
    @WebEndpoint(name = "PerfumeTransactionSoapServiceImplPort")
    public PerfumeTransactionSoapService getPerfumeTransactionSoapServiceImplPort() {
        return super.getPort(new QName("http://soap.perfume.hccis.ca/", "PerfumeTransactionSoapServiceImplPort"), PerfumeTransactionSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PerfumeTransactionSoapService
     */
    @WebEndpoint(name = "PerfumeTransactionSoapServiceImplPort")
    public PerfumeTransactionSoapService getPerfumeTransactionSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.perfume.hccis.ca/", "PerfumeTransactionSoapServiceImplPort"), PerfumeTransactionSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PERFUMETRANSACTIONSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
