
package org.example.soapperfume;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PerfumeTransactionSoapService", targetNamespace = "http://soap.perfume.hccis.ca/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PerfumeTransactionSoapService {


    /**
     * 
     * @param id
     * @return
     *     returns org.example.soapperfume.PerfumeTransaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://soap.perfume.hccis.ca/", className = "org.example.soapperfume.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://soap.perfume.hccis.ca/", className = "org.example.soapperfume.FindByIdResponse")
    @Action(input = "http://soap.perfume.hccis.ca/PerfumeTransactionSoapService/findByIdRequest", output = "http://soap.perfume.hccis.ca/PerfumeTransactionSoapService/findByIdResponse")
    public PerfumeTransaction findById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
